addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix"             % "0.12.1")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "1.22.0")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.3.2")
addSbtPlugin("com.github.sbt"     % "sbt-native-packager"      % "1.10.4")
addSbtPlugin("io.spray"           % "sbt-revolver"             % "0.10.0")
