object versions {
  val zioVersion           = "2.1.11"
  val zioHttpVersion       = "3.0.1"
  val zioJsonVersion       = "0.7.3"
  val zioProcessVersion    = "0.7.2"
  val laminarVersion       = "17.1.0"
  val frontrouteVersion    = "0.19.0"
  val fetchVersion         = "0.17.0"
  val zioPreludeVersion    = "1.0.0-RC31"
  val scalaJavaTimeVersion = "2.6.0"
  val jwtCoreVersion       = "10.0.1"
  val zioTestVersion       = "2.1.9"
  val zioQuillVersion      = "4.8.4"
  val mysqlVersion         = "8.0.33"
  val zioConfigVersion     = "4.0.2"
  val scalaShaVersion      = "2.0.2"
  val flywaydbVersion      = "10.19.0"
  val zioLoggingVersion    = "2.3.1"
  val chimneyVersion       = "1.11.0"
}
